version: "3.7"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    restart: unless-stopped
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    restart: unless-stopped
    depends_on:
      - zookeeper

  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb-kafka-user
      - MONGO_INITDB_ROOT_PASSWORD=mongodb-kafka-password
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 60s
      timeout: 10s
      retries: 5
    volumes:
      - mongodb-kafka-db-volume:/data/db

volumes:
  mongodb-kafka-db-volume: